name: Sample Github Action Workflow
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions-Dev:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT_NAME: ${{secrets.ENVIRONMENT_NAME}}
    environment:
      name: Dev
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "${{ env.ENVIRONMENT_NAME }}"" >> dev.txt
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dev-artifact
          path: |
            dev.txt
  Explore-GitHub-Actions-Staging:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT_NAME: ${{secrets.ENVIRONMENT_NAME}}
    environment:
      name: Staging
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "${{ env.ENVIRONMENT_NAME }}" >> staging.txt
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: staging-artifact
          path: |
            staging.txt
